<?php
/**
 * AddEvidenceResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayFulfillmentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayFulfillmentApi;

use PHPUnit\Framework\TestCase;

/**
 * AddEvidenceResponseTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the response payload of the addEvidence method. Its only field is an unique identifier of an evidence set.
 * @package     EbayFulfillmentApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddEvidenceResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddEvidenceResponse"
     */
    public function testAddEvidenceResponse()
    {
    }

    /**
     * Test attribute "evidence_id"
     */
    public function testPropertyEvidenceId()
    {
    }
}
