<?php
/**
 * AppliedPromotionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayFulfillmentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayFulfillmentApi;

use PHPUnit\Framework\TestCase;

/**
 * AppliedPromotionTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about a sales promotion that is applied to a line item.
 * @package     EbayFulfillmentApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AppliedPromotionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppliedPromotion"
     */
    public function testAppliedPromotion()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "promotion_id"
     */
    public function testPropertyPromotionId()
    {
    }
}
