<?php
/**
 * DisputeEvidenceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayFulfillmentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayFulfillmentApi;

use PHPUnit\Framework\TestCase;

/**
 * DisputeEvidenceTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the evidence array that is returned in the getPaymentDispute response if one or more evidential documents are associated with the payment dispute.
 * @package     EbayFulfillmentApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DisputeEvidenceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DisputeEvidence"
     */
    public function testDisputeEvidence()
    {
    }

    /**
     * Test attribute "evidence_id"
     */
    public function testPropertyEvidenceId()
    {
    }

    /**
     * Test attribute "evidence_type"
     */
    public function testPropertyEvidenceType()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "provided_date"
     */
    public function testPropertyProvidedDate()
    {
    }

    /**
     * Test attribute "request_date"
     */
    public function testPropertyRequestDate()
    {
    }

    /**
     * Test attribute "respond_by_date"
     */
    public function testPropertyRespondByDate()
    {
    }

    /**
     * Test attribute "shipment_tracking"
     */
    public function testPropertyShipmentTracking()
    {
    }
}
