<?php
/**
 * LineItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayFulfillmentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayFulfillmentApi;

use PHPUnit\Framework\TestCase;

/**
 * LineItemTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains the details of each line item in an order.
 * @package     EbayFulfillmentApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LineItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LineItem"
     */
    public function testLineItem()
    {
    }

    /**
     * Test attribute "applied_promotions"
     */
    public function testPropertyAppliedPromotions()
    {
    }

    /**
     * Test attribute "delivery_cost"
     */
    public function testPropertyDeliveryCost()
    {
    }

    /**
     * Test attribute "discounted_line_item_cost"
     */
    public function testPropertyDiscountedLineItemCost()
    {
    }

    /**
     * Test attribute "ebay_collect_and_remit_taxes"
     */
    public function testPropertyEbayCollectAndRemitTaxes()
    {
    }

    /**
     * Test attribute "gift_details"
     */
    public function testPropertyGiftDetails()
    {
    }

    /**
     * Test attribute "legacy_item_id"
     */
    public function testPropertyLegacyItemId()
    {
    }

    /**
     * Test attribute "legacy_variation_id"
     */
    public function testPropertyLegacyVariationId()
    {
    }

    /**
     * Test attribute "line_item_cost"
     */
    public function testPropertyLineItemCost()
    {
    }

    /**
     * Test attribute "line_item_fulfillment_instructions"
     */
    public function testPropertyLineItemFulfillmentInstructions()
    {
    }

    /**
     * Test attribute "line_item_fulfillment_status"
     */
    public function testPropertyLineItemFulfillmentStatus()
    {
    }

    /**
     * Test attribute "line_item_id"
     */
    public function testPropertyLineItemId()
    {
    }

    /**
     * Test attribute "listing_marketplace_id"
     */
    public function testPropertyListingMarketplaceId()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "purchase_marketplace_id"
     */
    public function testPropertyPurchaseMarketplaceId()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "sold_format"
     */
    public function testPropertySoldFormat()
    {
    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }
}
