<?php
/**
 * PaymentDisputeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EbayFulfillmentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * The version of the OpenAPI document: v1.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EbayFulfillmentApi;

use \EbayFulfillmentApi\Configuration;
use \EbayFulfillmentApi\ApiException;
use \EbayFulfillmentApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentDisputeApiTest Class Doc Comment
 *
 * @category Class
 * @package  EbayFulfillmentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentDisputeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptPaymentDispute
     *
     * Accept Payment Dispute.
     *
     */
    public function testAcceptPaymentDispute()
    {
    }

    /**
     * Test case for addEvidence
     *
     * Add an Evidence File.
     *
     */
    public function testAddEvidence()
    {
    }

    /**
     * Test case for contestPaymentDispute
     *
     * Contest Payment Dispute.
     *
     */
    public function testContestPaymentDispute()
    {
    }

    /**
     * Test case for fetchEvidenceContent
     *
     * Get Payment Dispute Evidence File.
     *
     */
    public function testFetchEvidenceContent()
    {
    }

    /**
     * Test case for getActivities
     *
     * Get Payment Dispute Activity.
     *
     */
    public function testGetActivities()
    {
    }

    /**
     * Test case for getPaymentDispute
     *
     * Get Payment Dispute Details.
     *
     */
    public function testGetPaymentDispute()
    {
    }

    /**
     * Test case for getPaymentDisputeSummaries
     *
     * Search Payment Dispute by Filters.
     *
     */
    public function testGetPaymentDisputeSummaries()
    {
    }

    /**
     * Test case for updateEvidence
     *
     * Update evidence.
     *
     */
    public function testUpdateEvidence()
    {
    }

    /**
     * Test case for uploadEvidenceFile
     *
     * Upload an Evidence File.
     *
     */
    public function testUploadEvidenceFile()
    {
    }
}
